#!/bin/bash
set -e

case "$1" in
    purge)
        # Remove configuration files on purge
        if [ -d /etc/monolith-firewall ]; then
            rm -rf /etc/monolith-firewall
        fi
        ;;
    remove)
        ;;
    upgrade|failed-upgrade|abort-upgrade)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'monolith-firewall-core.service' 'monolith-firewall-webui.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
