<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeLogic" Version="4.0.0" />
    <PackageReference Include="CodeLogic.SQLite" Version="4.0.1" />
  </ItemGroup>

</Project>
