using Monolith.FireWall.Common.Interfaces;
using Monolith.FireWall.Core.Models;

namespace Monolith.FireWall.Core.Services;

/// <summary>
/// Applies interface configurations from database on startup.
/// </summary>
public sealed class InterfaceConfigApplier
{
    private readonly ILogger _logger;
    private readonly InterfaceAssignmentStore _assignmentStore;
    private readonly InterfaceConfigManager _configManager;
    private readonly SystemSettingsManager _systemSettingsManager;

    public InterfaceConfigApplier(
        ILogger logger,
        InterfaceAssignmentStore assignmentStore,
        InterfaceConfigManager configManager,
        SystemSettingsManager systemSettingsManager)
    {
        _logger = logger;
        _assignmentStore = assignmentStore;
        _configManager = configManager;
        _systemSettingsManager = systemSettingsManager;
    }

    /// <summary>
    /// Apply stored interface configurations from database.
    /// </summary>
    public async Task<InterfaceConfigResult> ApplyStoredConfigsAsync(CancellationToken cancellationToken = default)
    {
        var result = new InterfaceConfigResult();

        try
        {
            // Read all interface assignments from database
            var assignments = await _assignmentStore.GetAssignmentsAsync();
            if (assignments.Count == 0)
            {
                result.Success = true;
                result.GeneratedCount = 0;
                result.Applied = false;
                _logger.LogInformation("No interface assignments found in database");
                return result;
            }

            // Get DNS servers from system settings
            var dnsServers = await _systemSettingsManager.GetDnsServersAsync();

            // Ensure include line exists in main interfaces file
            var (includeChanged, _) = await _configManager.EnsureIncludeAsync(cancellationToken);
            if (includeChanged)
            {
                _logger.LogInformation("Added include line to /etc/network/interfaces");
            }

            // Clean old managed config file to ensure fresh generation
            await CleanOldInterfaceConfigAsync(cancellationToken);

            // Generate and apply interface configuration
            var applyResult = await _configManager.ApplyAsync(assignments, dnsServers, cancellationToken);
            
            result.Success = true;
            result.GeneratedCount = assignments.Count;
            result.Applied = true;

            _logger.LogInformation($"Generated interface configuration for {assignments.Count} interface(s)");
            
            if (!string.IsNullOrWhiteSpace(applyResult.BackupFile))
            {
                _logger.LogInformation($"Backed up previous config to: {applyResult.BackupFile}");
            }
        }
        catch (Exception ex)
        {
            result.Success = false;
            result.Error = ex.Message;
            _logger.LogError(ex, "Failed to apply interface configurations");
        }

        return result;
    }

    /// <summary>
    /// Clean old interface config file to ensure fresh generation.
    /// </summary>
    private async Task CleanOldInterfaceConfigAsync(CancellationToken cancellationToken)
    {
        const string managedFilePath = "/etc/network/interfaces.d/monolith";
        
        if (!File.Exists(managedFilePath))
        {
            return;
        }

        try
        {
            // Read existing file to check if it's managed
            var content = await File.ReadAllTextAsync(managedFilePath, cancellationToken);
            var isManaged = content.Contains("# BEGIN MONOLITH MANAGED", StringComparison.OrdinalIgnoreCase) ||
                           content.Contains("# Generated by Monolith FireWall", StringComparison.OrdinalIgnoreCase);

            if (isManaged)
            {
                // Backup and delete managed file
                var backupDir = "/var/lib/monolith-firewall/backups/interfaces";
                Directory.CreateDirectory(backupDir);
                var timestamp = DateTime.UtcNow.ToString("yyyyMMddHHmmss");
                var backupPath = Path.Combine(backupDir, $"monolith.bak-{timestamp}");
                
                File.Copy(managedFilePath, backupPath, overwrite: true);
                File.Delete(managedFilePath);
                
                _logger.LogInformation($"Cleaned old managed interface config: {managedFilePath} -> {backupPath}");
            }
            else
            {
                // File exists but not managed - backup and warn
                var backupDir = "/var/lib/monolith-firewall/backups/interfaces";
                Directory.CreateDirectory(backupDir);
                var timestamp = DateTime.UtcNow.ToString("yyyyMMddHHmmss");
                var backupPath = Path.Combine(backupDir, $"monolith-unmanaged.bak-{timestamp}");
                
                File.Copy(managedFilePath, backupPath, overwrite: true);
                File.Delete(managedFilePath);
                
                _logger.LogWarning($"Found unmanaged interface config file, backed up and will overwrite: {managedFilePath} -> {backupPath}");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error cleaning old interface config: {ex.Message}");
            // Continue anyway - the ApplyAsync will handle it
        }
    }
}
